name: 掘金自动化工作流
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0/1 * * *

jobs:
  followUser:
    name: 关注掘金用户的关注动态
    runs-on: ubuntu-latest
    env:
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      QQ_MAIL_PASSWORD: ${{ secrets.QQ_MAIL_PASSWORD }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      - name: 设置 Python 版本
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: 安装依赖并运行 python 脚本
        run: |
          pip install requests
          python Juejin/followUser.py